### ISSUE TITLE
Puzzle Preview Crashes On Load

### ISSUE THREAD

**Issue by masalt2** [electrovoyage/beeMMX-R#14]
When I have my song package loaded into BEEmod and I try to preview my puzzle, the engine crashes.
![image](https://github.com/TPEcool/beeMMX-R/assets/122125545/1d7b11d2-ded4-49d3-8db8-c9f31bb4e580)

**Comment by TPEcool** [comment]
Can you open your music in Audacity and show the sample rate (must be 44100, limitation of P2's audio engine) and the sample format (must be 16-bit PCM or something like that, forgot)? The audio engine will crash when one of these is wrong.

**Comment by masalt2** [comment]
It was my fault, the audio used 32-bit float.

**Comment by TPEcool** [comment]
So that's why BMMC2 literally doesn't even show 32-bit float WAV files.
